### ISSUE TITLE
missing data folder GiuseppeToys 

### ISSUE THREAD

**Issue by jamesl-github** [PacktPublishing/Deep-Learning-with-PyTorch-Quick-Start-Guide#2]
Chapter 1: Introduction to Pytorch 
Section Loading Data 
says  "For this example, I have created a smaller subset of the dataset, together with a labels.csv file. This is available in the data/GiuseppeToys folder in the GitHub repository for this book. " 

The GiuseppeToys is missing.

**Comment by vishwesh5** [comment]
Hi!

The **labels.csv** file is present in **Chapter01/GuiseppeToys/**.
